# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11b825bb327a9fd8d267e40e229fa60d2f750c286647078728806e63dbd9104ef80103c3f7682fc76d50c19cbb3d189c4ab12062ad7ee346c70cbe9510e61dc7
  client_id: "738059284424-ogvblj3h6r883u423c71h5phuaoccffj.apps.googleusercontent.com"
  client_secret: "LLbuH9r2dtHcFJQ4iw2vuL-t"
test:
  secret_key_base: 8099b52c2f0a5abad41ad03c4a66bebd09ec191295245fd9c1b68211725c92ba1983248156cedb7de6a22c876fd0362ed4ccdb4ee8a4c5397fa548cdacf8d8a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
